export const API_URL = {
    signup: 'signup',
    login: 'admins/login',
    image:'http://localhost:3001/image',
    // image:'http://44.219.107.26:3001/image',
    create_race: 'admins/post_race',
    getALLUserdetails: 'admins/getALLUserdetails',
    todays_tips: 'admins/todays_tips',
    get_todaystips: 'admins/getAdminTodaysTips',
    get_AllRaces: 'admins/get_allRaces',
    getRaceById: 'admins/allRaceData/',
    getAllllAdminTips: 'admins/getAllllAdminTips',
    updateTip: 'admins/updateTodays_tips',
    getTipsById: 'admins/getTipById/',
    getTipsByRaceId: 'admins/getTipsByRaceId/',
    resultdeclaration:'admins/resultdeclaration',
    updatehomesection_1:'admins/update_home_section_1',
    updatehomesection_2:'admins/update_home_section_2',
    updatehomesection_4:'admins/update_home_section_4',
    upload3:'admins/upload_home_section_3',
    getSection1:'admins/getSection1',
    getSection2:'admins/getSection2',
    getSection3:'admins/getSection3',
    getSection4:'admins/getSection4',
    deleteSection3:'admins/deleteSection3/',
    getTipsManagement:'admins/getTipsManagement',
    createTips:'admins/createTips',
    updateTipsCms:'admins/updateTipsCms',
    updateContactCms:'admins/updateContactCms',
    get_tips_cms:'admins/get_tips_cms/',
    deleteTips:'admins/delete_tips_cms/',
    deleteVenue:'admins/delete_venue_cms/',
    venueUpload:'admins/venue_cms',
    getAllVenue:'admins/getVenue',
    get_venue_cms:'admins/get_venue_cms/',
    updateVenue_Cms:'admins/updateVenueCms',
    getContactManagement:'admins/getContactManagement',
    getHorsesManagement:'admins/getHorsesManagement',
    horses_cms:'admins/horses_cms',
    updateHorses_cms:'admins/updateHorses_cms',
    get_horses_cms:'admins/get_horses_cms/',
    delete_horses_cms:'admins/delete_horses_cms/',
    delete_races_cms:'admins/delete_races_cms/',
    getContacts:'admins/getContacts',
    updateMisc:'admins/update_misc',
    getMisc:'admins/getMisc',
    get_RacesCMSId:'admins/get_Races_cms/',
    getRaceManagement:'admins/getRaceManagement',
    update_race_cms:'admins/update_race_cms',
    uploadRace_cms:'admins/uploadRace_cms',
    getBettingByUserId:'admins/getBettingByUserId/',
    getUserDetailsId:'admins/getUserDetailsId/',
    getUserPayment_bids:'admins/getUserPayment_bids/',
    update_the_system:'admins/update_the_system',
    updateOnTheDayTable:'admins/updateOnTheDayTable',
    getHowitWorks:'admins/getHowitWorks',
    update_horse_racing_tips:'admins/update_horse_racing_tips',
    getHorseRacingTips:'admins/getHorseRacingTips',
    updateFAQData:'admins/updateFAQData',
    updateTermsConditionsData:'admins/updateTermsConditionsData',
    upload_venues:'admins/upload_venues',
    upload_cities:'admins/upload_cities',
    getVeneus:'admins/getVeneus',
    getCities:'admins/getCities',

    
}